# Generated by Django 5.2.17 on 2026-08-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
